### ISSUE TITLE
Update build tags on Docker Hub

### ISSUE THREAD

**Issue by ruimarinho** [clkao/docker-postgres-plv8#7]
@clkao we need to update the tags to point to the correct Dockerfiles on Docker Hub as right now the 1.5 builds is pointing to the 1.4 build.

**Comment by clkao** [comment]
This should be fixed now.

**Comment by ruimarinho** [comment]
Setup looks good, but somehow builds are failing? https://hub.docker.com/r/clkao/postgres-plv8/builds/

Since logs are empty, can you see if retrying them helps?

**Comment by clkao** [comment]
weird. it is still failing with empty logs. might need to contact docker hub support

**Comment by ruimarinho** [comment]
Even though the original issue is still there, we can keep tracking this on `docker/hub-feedback` repository as the new builds are working fine now.
